# NOTE: The EbbRT toolchain is required to build Om
#       Set EBBRT_SYSROOT env variable to its (default: /opt/ebbrt)
EBBRT_SYSROOT ?= $(abspath /opt/ebbrt)
EBBRT_BIN_DIR=${EBBRT_SYSROOT}/usr/bin
EBBRT_CC:=${CC} #${EBBRT_BIN_DIR}/x86_64-pc-ebbrt-gcc
EBBRT_LD:=${LD} #${EBBRT_BIN_DIR}/x86_64-pc-ebbrt-ld

$(EBBRT_SYSROOT): # verify we have an EbbRT toolchain
	$(error EBBRT_SYSROOT is undefined and can not be located)

EBBRT_CFLAGS:= #${CFLAGS}
EBBRT_LDFLAGS:= #${LDFLAGS}
